### ISSUE TITLE
Scrambled display

### ISSUE THREAD

**Issue by tatref** [amnrst/youtube-like-to-view-ratio#1]
Thanks for this extension!

Sometime, the display gets scrambled:

![image](https://user-images.githubusercontent.com/2582791/144727615-b9693ecf-23d4-4fa1-98cd-2df4de3660b4.png)

Refreshing the page fixes the issue most of the times.

**Comment by aminroosta** [comment]
Could you try v0.0.0.2, it should be fixed in the newer version.

**Comment by tatref** [comment]
Seems to be fixed!
