### ISSUE TITLE
Youtube UI redesign incompatible

### ISSUE THREAD

**Issue by ethanqm** [amnrst/youtube-like-to-view-ratio#11]
![image](https://user-images.githubusercontent.com/102937457/199146280-18dd2439-f2c7-4eb5-934d-325a8dc4f048.png)

These design changes are usually rolled out to users incrementally, and I just got this today

**Comment by aminroosta** [comment]
I've submitted `v0.0.1.0` for review.
This new version works only with the updated youtube UI Design & is backward incompatible. 

Once it is published (usually takes a couple of hours), please let me know if it works for you.

**Comment by ethanqm** [comment]
![image](https://user-images.githubusercontent.com/102937457/199368659-27dfb1bf-8fff-4ae2-9950-d7c38069dc3c.png)

Looks great. Minor bug where it disappears when disliking while liked, but purpose served at that point haha
