### ISSUE TITLE
Likes / views regex does not work with non-latin symbols

### ISSUE THREAD

**Issue by ap32** [amnrst/youtube-like-to-view-ratio#2]
use ```str.replace(/\D/g, '');``` instead

**Comment by aminroosta** [comment]
Could you send me an MR?
If you had it tested, I’ll publish your change as a new version.

**Comment by ap32** [comment]
@aminroosta No, but i tested regex. ```'36 738 отметок "Нравится"'.replace(/\D/g, '');``` returns ```'36738'```

**Comment by aminroosta** [comment]
Thanks @AlexOrtizzz, that seems good enough.
I've changed that regex and uploaded v0.0.0.3 for review.
It should be approved in a few hours hopefully.

**Comment by aminroosta** [comment]
@AlexOrtizzz OK the one for firefox got approved just now 😃

**Comment by ap32** [comment]
@aminroosta i believe, i found another bug, 
```const likesEl = infoEl.querySelector('yt-formatted-string[aria-label~="likes"]');``` won't work in most cases too.
```document.querySelector('ytd-menu-renderer.ytd-video-primary-info-renderer yt-formatted-string');``` works for me.
Something like ```const likesEl = infoEl.querySelector('ytd-menu-renderer.ytd-video-primary-info-renderer yt-formatted-string');``` might work, please check.

**Comment by aminroosta** [comment]
@AlexOrtizzz you are right, fixed that bit as well & published v0.0.0.4 just now.
This time I tested it out, seemed to be working fine - should be public in a few hours.

**Comment by aminroosta** [comment]
Ok, the firefox version just went public 🏆

**Comment by ap32** [comment]
@aminroosta it works in chromium 🎉 Thank you very much 😊
![image](https://user-images.githubusercontent.com/12585904/145081608-3dd1ae72-03da-4a9f-a0a2-7a1f3a90946d.png)
