### ISSUE TITLE
Firefox mobile?

### ISSUE THREAD

**Issue by omar-selo** [amnrst/youtube-like-to-view-ratio#4]
Would it be possible to add the extension to Firefox mobile

**Comment by aminroosta** [comment]
I haven't tested it on android firefox, since I'm using iphone myself.
Could you help test it locally? and if it works, I'll publish a new version.

**Comment by aminroosta** [comment]
The new version `0.0.7` will be available in a few hours.
I enabled it for firefox mobile, even thought it's not tested at all.

Give it a try, maybe it works!.
