### ISSUE TITLE
likesEl querySelector doesn't work properly with geotag

### ISSUE THREAD

**Issue by ap32** [amnrst/youtube-like-to-view-ratio#5]
![image](https://user-images.githubusercontent.com/12585904/145544790-76bc77bd-6304-4369-a839-094d813803f4.png)
[from here](https://www.youtube.com/watch?v=bikbJPI-7Kg)

```document.querySelector("ytd-video-primary-info-renderer").querySelector('ytd-menu-renderer.ytd-video-primary-info-renderer yt-formatted-string[aria-label]')``` works for me.

**Comment by aminroosta** [comment]
Thank you for the bug report - I'll fix it.

**Comment by aminroosta** [comment]
Fixed in v0.0.0.5 & published.
Should be public in a few hours.
