### ISSUE TITLE
Hide on live streaming

### ISSUE THREAD

**Issue by barn852** [amnrst/youtube-like-to-view-ratio#9]
Since live streaming shows the active views (watching now), the percentage of likes is quite high and has no significant information.

I suggest to hide it on live views.

**Comment by barn852** [comment]
I just added `if (views.includes("watching now")) return null;` after line 10, it looks like it's working.
(tested on violentmonkey)

**Comment by aminroosta** [comment]
I just submitted `0.0.7` with the new fix.
It'll be published in about a day.

Please reopen if it doesn't work.
